'use client';

import * as React from 'react';
import dynamic from 'next/dynamic';
import { useQuery } from '@tanstack/react-query';
import { Activity, MousePointerClick, Send, ShoppingBag, TrendingUp, Zap } from 'lucide-react';
import { CHANNEL_LABELS, formatInrCompact, formatPercent } from '@scp/shared';
import { api, ApiError } from '@/lib/api';
import { ATTRIBUTION_REVENUE_LABEL, ATTRIBUTION_TOOLTIP } from '@/lib/attribution-copy';
import type { CampaignDetail, CampaignMetricsResponse } from '@/lib/types';
import { CampaignAudienceCard } from '@/components/campaigns/campaign-audience-card';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { ProgressBar } from '@/components/ui/misc';
import { Skeleton } from '@/components/ui/skeleton';
import { StatCard } from '@/components/shared/stat-card';
import { ChannelBadge } from '@/components/shared/labels';
import {
  CampaignWorkspaceNotFound,
  isCampaignNotFoundError,
} from '@/components/campaigns/campaign-workspace-not-found';
import { useBrand } from '@/contexts/brand-context';

// Heavy / below-the-fold components are lazy-loaded.
const TimelineChart = dynamic(() => import('./timeline-chart'), {
  ssr: false,
  loading: () => <Skeleton className="h-56 w-full" />,
});
const InsightsPanel = dynamic(() => import('./insights-panel'), {
  ssr: false,
  loading: () => <Skeleton className="h-64 w-full rounded-xl" />,
});

function isMetricsSettled(metrics: CampaignMetricsResponse['metrics'] | undefined): boolean {
  return Boolean(metrics && metrics.queued === 0 && metrics.sent >= metrics.targeted);
}

export function CampaignMonitor({ campaign }: { campaign: CampaignDetail }) {
  const { selectedBrandId } = useBrand();
  const { data, isLoading, isError, error } = useQuery<CampaignMetricsResponse>({
    queryKey: ['metrics', selectedBrandId, campaign.id],
    queryFn: () => api.campaignMetrics(campaign.id),
    enabled: Boolean(selectedBrandId),
    retry: (_count, err) => !(err instanceof ApiError && err.status === 404),
    refetchInterval: (query) => {
      if (query.state.error instanceof ApiError && query.state.error.status === 404) return false;
      return isMetricsSettled(query.state.data?.metrics) ? false : 3000;
    },
  });

  if (isError && isCampaignNotFoundError(error)) {
    return <CampaignWorkspaceNotFound />;
  }

  if (isLoading || !data) {
    return (
      <div className="space-y-6">
        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
          {Array.from({ length: 6 }).map((_, i) => (
            <Skeleton key={i} className="h-28 rounded-xl" />
          ))}
        </div>
        <Skeleton className="h-72 rounded-xl" />
      </div>
    );
  }

  const m = data.metrics;
  const funnel = [
    { label: 'Targeted', value: m.targeted },
    { label: 'Sent', value: m.sent },
    { label: 'Delivered', value: m.delivered },
    { label: 'Read', value: m.read },
    { label: 'Clicked', value: m.clicked },
    { label: 'Converted', value: m.attributedOrders },
  ];
  const maxFunnel = Math.max(1, m.targeted);
  const settled = isMetricsSettled(m);
  const live = !settled && m.queued > 0;

  return (
    <div className="space-y-6">
      <CampaignAudienceCard campaign={campaign} />

      <p className="text-xs text-muted-foreground">
        Simulated campaign data — metrics below are generated by the channel simulator, not live production CRM data.
      </p>

      {live && (
        <div className="inline-flex items-center gap-2 rounded-full bg-primary/10 px-3 py-1 text-xs font-medium text-primary">
          <span className="relative flex size-2">
            <span className="absolute inline-flex size-full animate-ping rounded-full bg-primary opacity-60" />
            <span className="relative inline-flex size-2 rounded-full bg-primary" />
          </span>
          Live — events streaming in
        </div>
      )}

      {/* KPIs */}
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
        <StatCard label="Sent" value={m.sent.toLocaleString('en-IN')} icon={Send} hint={`${m.failed} failed`} />
        <StatCard label="Delivered" value={m.delivered.toLocaleString('en-IN')} icon={Activity} hint={formatPercent(m.deliveryRate)} />
        <StatCard label="Clicked" value={m.clicked.toLocaleString('en-IN')} icon={MousePointerClick} hint={formatPercent(m.clickRate)} />
        <StatCard label="Simulated attributed orders" value={m.attributedOrders.toLocaleString('en-IN')} icon={ShoppingBag} hint={formatPercent(m.conversionRate)} hintTitle={ATTRIBUTION_TOOLTIP} />
        <StatCard label={ATTRIBUTION_REVENUE_LABEL} value={formatInrCompact(m.attributedRevenue)} icon={TrendingUp} accent hintTitle={ATTRIBUTION_TOOLTIP} />
        <StatCard
          label="Lift vs control"
          value={m.liftVsControl > 0 ? `${formatPercent(m.liftVsControl, 0)}` : '—'}
          icon={Zap}
          accent
          hint={`Control conv. ${formatPercent(m.controlConversionRate)}`}
        />
      </div>

      <div className="grid gap-6 lg:grid-cols-3">
        {/* Funnel */}
        <Card className="lg:col-span-1">
          <CardHeader>
            <CardTitle>Delivery funnel</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            {funnel.map((f) => (
              <div key={f.label} className="space-y-1.5">
                <div className="flex items-center justify-between text-sm">
                  <span className="text-muted-foreground">{f.label}</span>
                  <span className="font-medium tabular-nums">{f.value.toLocaleString('en-IN')}</span>
                </div>
                <ProgressBar value={f.value / maxFunnel} />
              </div>
            ))}
          </CardContent>
        </Card>

        {/* Timeline chart */}
        <Card className="lg:col-span-2">
          <CardHeader>
            <CardTitle>Engagement over time</CardTitle>
          </CardHeader>
          <CardContent>
            <TimelineChart events={data.timeline} />
          </CardContent>
        </Card>
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        {/* Channel breakdown */}
        <Card>
          <CardHeader>
            <CardTitle>Channel performance</CardTitle>
            <p className="text-xs text-muted-foreground" title={ATTRIBUTION_TOOLTIP}>
              Simulated sends by actual delivery channel. Revenue column shows {ATTRIBUTION_REVENUE_LABEL.toLowerCase()}.
            </p>
          </CardHeader>
          <CardContent className="space-y-4">
            {data.channels.length === 0 ? (
              <p className="text-sm text-muted-foreground">No channel data yet.</p>
            ) : (
              data.channels.map((c) => (
                <div key={c.channel} className="flex items-center justify-between gap-4">
                  <div className="flex items-center gap-2">
                    <ChannelBadge channel={c.channel} />
                  </div>
                  <div className="flex items-center gap-6 text-sm">
                    <span className="tabular-nums text-muted-foreground">{c.sent.toLocaleString('en-IN')} sent</span>
                    <span className="tabular-nums">{formatPercent(c.sent ? c.clicked / c.sent : 0)} CTR</span>
                    <span className="w-20 text-right font-medium tabular-nums">{formatInrCompact(c.attributedRevenue)}</span>
                  </div>
                </div>
              ))
            )}
          </CardContent>
        </Card>

        {/* Variant A/B */}
        <Card>
          <CardHeader>
            <CardTitle>A/B variant performance</CardTitle>
            <p className="text-xs text-muted-foreground">
              Sent/click counts match channel performance (by actual send channel).
            </p>
          </CardHeader>
          <CardContent className="space-y-4">
            {data.variants.map((v) => (
              <div key={v.label} className="space-y-2">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Badge variant="primary">Variant {v.label}</Badge>
                    <ChannelBadge channel={v.channel} />
                  </div>
                  <span className="text-sm font-medium tabular-nums">{formatPercent(v.conversionRate)} conv.</span>
                </div>
                <ProgressBar value={v.conversionRate * 5} barClassName="bg-accent" />
                <div className="flex gap-4 text-xs text-muted-foreground">
                  <span>{v.sent.toLocaleString('en-IN')} sent</span>
                  <span>{v.clicked.toLocaleString('en-IN')} clicked</span>
                  <span>{v.attributed.toLocaleString('en-IN')} converted</span>
                </div>
              </div>
            ))}
          </CardContent>
        </Card>
      </div>

      {/* AI insights (lazy) — only after simulation settles */}
      <InsightsPanel campaignId={campaign.id} metricsSettled={settled} />
    </div>
  );
}
