import type { ZodType } from 'zod';
import { AiCapability } from '@scp/shared';
import type { AiContext, AiResult, Capability } from './types.js';
import { callOpenAi } from './providers/openai.js';
import { buildAnalysisFromMetrics } from './capabilities/analyze-performance.js';
import type { AnalyzeCampaignPerformanceInput } from './inputs.js';

/**
 * Execute a capability with the configured provider. Guarantees a structured,
 * schema-valid result: if the real model fails or returns malformed JSON we fall
 * back to the deterministic mock and mark the run as FALLBACK.
 */
export async function runCapability<I, O>(
  capability: Capability<I, O>,
  outputSchema: ZodType<O>,
  input: I,
  ctx: AiContext,
): Promise<AiResult<O>> {
  const started = Date.now();

  if (ctx.provider === 'openai') {
    try {
      const raw = await callOpenAi(capability.buildPrompt(input), capability.schemaHint, ctx);
      let parsed = outputSchema.parse(raw) as O;
      if (capability.name === AiCapability.ANALYZE_CAMPAIGN_PERFORMANCE) {
        parsed = buildAnalysisFromMetrics(input as AnalyzeCampaignPerformanceInput) as O;
      }
      return {
        result: parsed,
        explanation:
          capability.name === AiCapability.ANALYZE_CAMPAIGN_PERFORMANCE
            ? (parsed as { summary?: string }).summary ?? 'Generated from settled campaign metrics.'
            : extractExplanation(raw) ?? 'Generated by OpenAI.',
        confidence: extractConfidence(raw) ?? 0.75,
        provider: 'openai',
        model: ctx.model,
        status: 'SUCCESS',
        latencyMs: Date.now() - started,
      };
    } catch {
      // Fall through to deterministic mock.
      const m = capability.mock(input);
      return {
        ...m,
        provider: 'openai',
        model: ctx.model,
        status: 'FALLBACK',
        latencyMs: Date.now() - started,
      };
    }
  }

  const m = capability.mock(input);
  return {
    ...m,
    provider: 'mock',
    status: 'SUCCESS',
    latencyMs: Date.now() - started,
  };
}

function extractExplanation(raw: unknown): string | undefined {
  if (raw && typeof raw === 'object' && 'explanation' in raw) {
    const v = (raw as Record<string, unknown>).explanation;
    return typeof v === 'string' ? v : undefined;
  }
  return undefined;
}

function extractConfidence(raw: unknown): number | undefined {
  if (raw && typeof raw === 'object' && 'confidence' in raw) {
    const v = (raw as Record<string, unknown>).confidence;
    return typeof v === 'number' ? v : undefined;
  }
  return undefined;
}

export function resolveAiContext(env: NodeJS.ProcessEnv = process.env): AiContext {
  const provider = env.AI_PROVIDER === 'openai' && env.OPENAI_API_KEY ? 'openai' : 'mock';
  return {
    provider,
    apiKey: env.OPENAI_API_KEY,
    model: env.OPENAI_MODEL ?? 'gpt-4o-mini',
  };
}
